### ISSUE TITLE
Model availability

### ISSUE THREAD

**Issue by rohithkodali** [oaarnikoivu/ainoa#1]
By Any chance is there a way to release the model to public or at least the data set info used for training?

**Comment by oaarnikoivu** [comment]
Hey, the dataset that was used is called: 
2018 SemEval Task 1 E-c (multi label emotion classification) dataset. 

The model itself is too large to host through GitHub but it should be easily reproducible through the code in the notebooks folder.

**Comment by rohithkodali** [comment]
thanks a lot i will retrain using the code, i have downloaded that dataset
